export const images = {
    lostArkImage: require('./image.svg'),
    classIconAssassin: require('./classicon-assassin.png'),
    classIconGunner: require('./classicon-gunner.png'),
    classIconMage: require('./classicon-mage.png'),
    classIconMartialArtist: require('./classicon-martial-artist.png'),
    classIconWarrior: require('./classicon-warrior.png'),
    classIconSpecialist: require('./specialist-artist.png'),
    Line: require('./line-1.svg'),
    BG: require('./main-app-bg-1920.png'),
    magnifyingGlass: require('./magnifying-glass-solid-1.svg'),
    rightToBracket: require('./right-to-bracket-solid-1.svg'),
    scooter: require('./scooter.png'),
    loaIcon: require('./loa-icon.png'),
  };